class Doctor {
  final String name;
  final String specialty;
  final String hospital;
  final double rating;
  final int reviews;
  final String image;
  final int patients;
  final int experience;
  final String about;
  final List<String> workingDays;
  final String workingHours;

  Doctor({
    required this.name,
    required this.specialty,
    required this.hospital,
    required this.rating,
    required this.reviews,
    required this.image,
    this.patients = 0,
    this.experience = 0,
    this.about = '',
    this.workingDays = const [],
    this.workingHours = '',
  });
}

// Sample data
List<Doctor> sampleDoctors = [
  Doctor(
    name: 'Dr. Marcus Horizon',
    specialty: 'Cardiologist',
    hospital: 'Cardiology Center, USA',
    rating: 4.7,
    reviews: 2872,
    image: 'assets/images/artur-tumasjan-qLzWvcQq-V8-unsplash.jpg',
    patients: 2000,
    experience: 10,
    about: 'Dr. Marcus Horizon is a top specialist at London Bridge Hospital. He has achieved several awards and recognition for his contribution to the medical field and cardiology research.',
    workingDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    workingHours: '09:00 AM - 05:00 PM',
  ),
  Doctor(
    name: 'Dr. Maria Elena',
    specialty: 'Psychologist',
    hospital: 'Mental Health Center, USA',
    rating: 4.9,
    reviews: 1653,
    image: 'assets/images/linkedin-sales-solutions-pAtA8xe_iVM-unsplash.jpg',
    patients: 1500,
    experience: 8,
    about: 'Experienced psychologist specializing in cognitive behavioral therapy and mental health counseling. Dedicated to helping patients achieve better mental wellbeing.',
    workingDays: ['Monday', 'Wednesday', 'Friday'],
    workingHours: '10:00 AM - 06:00 PM',
  ),
  Doctor(
    name: 'Dr. Luke Whitesell',
    specialty: 'Dentist',
    hospital: 'Dental Care Center, USA',
    rating: 4.8,
    reviews: 2156,
    image: 'assets/images/bruno-rodrigues-279xIHymPYY-unsplash.jpg',
    patients: 1800,
    experience: 12,
    about: 'Expert dentist with focus on cosmetic dentistry and oral surgery. Committed to providing painless dental care with the latest technology.',
    workingDays: ['Tuesday', 'Thursday', 'Saturday'],
    workingHours: '08:00 AM - 04:00 PM',
  ),
  Doctor(
    name: 'Dr. Alysa Hana',
    specialty: 'Dermatologist',
    hospital: 'Skin Care Center, USA',
    rating: 4.6,
    reviews: 1891,
    image: 'assets/images/ashkan-forouzani-DPEPYPBZpB8-unsplash.jpg',
    patients: 1200,
    experience: 7,
    about: 'Specialized in treating skin conditions and cosmetic procedures. Expert in anti-aging treatments and dermatological surgery.',
    workingDays: ['Monday', 'Tuesday', 'Thursday', 'Friday'],
    workingHours: '09:00 AM - 05:00 PM',
  ),
  Doctor(
    name: 'Dr. Joseph Brostito',
    specialty: 'General Physician',
    hospital: 'General Hospital, New York',
    rating: 4.8,
    reviews: 3421,
    image: 'assets/images/bruno-rodrigues-BCUUAsPECK4-unsplash.jpg',
    patients: 2500,
    experience: 15,
    about: 'General physician with extensive experience in family medicine. Provides comprehensive healthcare services for patients of all ages.',
    workingDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    workingHours: '08:00 AM - 06:00 PM',
  ),
  Doctor(
    name: 'Dr. Sarah Mitchell',
    specialty: 'Pediatrician',
    hospital: 'Children\'s Hospital, Boston',
    rating: 4.9,
    reviews: 2987,
    image: 'assets/images/mohamad-azaam-1O8CJy1A7Wo-unsplash.jpg',
    patients: 1900,
    experience: 11,
    about: 'Pediatrician specializing in child healthcare and development. Passionate about ensuring the health and wellbeing of children.',
    workingDays: ['Monday', 'Wednesday', 'Friday', 'Saturday'],
    workingHours: '09:00 AM - 05:00 PM',
  ),
  Doctor(
    name: 'Dr. Robert Chen',
    specialty: 'Orthopedic Surgeon',
    hospital: 'Orthopedic Center, Chicago',
    rating: 4.7,
    reviews: 2134,
    image: 'assets/images/humberto-chavez-FVh_yqLR9eA-unsplash.jpg',
    patients: 1600,
    experience: 14,
    about: 'Orthopedic surgeon with expertise in joint replacement and sports medicine. Dedicated to helping patients regain mobility and quality of life.',
    workingDays: ['Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    workingHours: '08:00 AM - 04:00 PM',
  ),
  Doctor(
    name: 'Dr. Emily Watson',
    specialty: 'Neurologist',
    hospital: 'Neurology Institute, California',
    rating: 4.8,
    reviews: 1765,
    image: 'assets/images/mohamad-azaam-njTNSYPOaUE-unsplash.jpg',
    patients: 1400,
    experience: 9,
    about: 'Neurologist specializing in brain and nervous system disorders. Expert in treating migraines, epilepsy, and neurodegenerative diseases.',
    workingDays: ['Monday', 'Tuesday', 'Thursday', 'Friday'],
    workingHours: '09:00 AM - 05:00 PM',
  ),
  Doctor(
    name: 'Dr. James Anderson',
    specialty: 'ENT Specialist',
    hospital: 'ENT Care Center, Miami',
    rating: 4.6,
    reviews: 1543,
    image: 'assets/images/sander-sammy-38Un6Oi5beE-unsplash.jpg',
    patients: 1300,
    experience: 10,
    about: 'ENT specialist with expertise in ear, nose, and throat disorders. Provides comprehensive treatment for sinus issues, hearing problems, and throat conditions.',
    workingDays: ['Monday', 'Wednesday', 'Thursday', 'Friday'],
    workingHours: '10:00 AM - 06:00 PM',
  ),
  Doctor(
    name: 'Dr. Lisa Brown',
    specialty: 'Ophthalmologist',
    hospital: 'Eye Care Institute, Seattle',
    rating: 4.9,
    reviews: 2456,
    image: 'assets/images/usman-yousaf-PVjfLss3b-c-unsplash.jpg',
    patients: 1700,
    experience: 13,
    about: 'Ophthalmologist specializing in eye care and vision correction. Expert in cataract surgery, LASIK, and treatment of eye diseases.',
    workingDays: ['Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    workingHours: '08:00 AM - 05:00 PM',
  ),
  Doctor(
    name: 'Dr. Michael Zhang',
    specialty: 'Gastroenterologist',
    hospital: 'Digestive Health Center, Houston',
    rating: 4.7,
    reviews: 1876,
    image: 'assets/images/vaibhav-vivian-3HIroMoyre8-unsplash.jpg',
    patients: 1500,
    experience: 12,
    about: 'Gastroenterologist with expertise in digestive system disorders. Specializes in treating conditions like IBS, Crohn\'s disease, and liver problems.',
    workingDays: ['Monday', 'Tuesday', 'Wednesday', 'Friday'],
    workingHours: '09:00 AM - 05:00 PM',
  ),
  Doctor(
    name: 'Dr. Amanda Foster',
    specialty: 'Dentist',
    hospital: 'Modern Dental Clinic, Austin',
    rating: 4.8,
    reviews: 2234,
    image: 'assets/images/diana73-dentist-1191671_1920.jpg',
    patients: 1650,
    experience: 8,
    about: 'Dental specialist focused on preventive care and cosmetic dentistry. Provides comprehensive dental services including cleanings, fillings, and teeth whitening.',
    workingDays: ['Monday', 'Tuesday', 'Thursday', 'Saturday'],
    workingHours: '08:00 AM - 04:00 PM',
  ),
  Doctor(
    name: 'Dr. David Kumar',
    specialty: 'General Surgeon',
    hospital: 'Surgical Center, Denver',
    rating: 4.9,
    reviews: 3102,
    image: 'assets/images/granderboy-doctor-2337835_1920.jpg',
    patients: 2200,
    experience: 16,
    about: 'General surgeon with extensive experience in minimally invasive surgery. Specializes in laparoscopic procedures and emergency surgery.',
    workingDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    workingHours: '07:00 AM - 05:00 PM',
  ),
];
